name: Update copyright year(s) in license file

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 1 1 *'

jobs:
  copyright:
    uses: ./.github/workflows/update-copyright-years-in-license-file.yaml
    secrets: inherit
